# Generated by Django 4.1.1 on 2022-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0002_alter_bares_email_alter_heladerias_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bares',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bares'),
        ),
    ]
