# Generated by Django 4.1.1 on 2022-11-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0003_bares_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bares',
            name='imagen',
        ),
    ]
